// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvwpsbbaulvnicjhaesi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2d3BzYmJhdWx2bmljamhhZXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTcyODUsImV4cCI6MjA2ODg3MzI4NX0.yDvi63xIuobIXJ57djyAoWZwiiiYwdfwK7BgCvLDit4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});